process.env.ENV = 'test'
process.env.NODE_ENV = 'test'
process.env.ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET || 'test-access-secret'
process.env.REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET || 'test-refresh-secret'
process.env.DATABASE_URL = process.env.DATABASE_URL || 'mongodb://127.0.0.1:27017/base-server-test'
